### ISSUE TITLE
Error with dnf module on Fedora 22

### ISSUE THREAD

**Issue by wowi42** [ansible/ansible-modules-extras#471]
# Issue Type:

Bug Report
# Ansible Version:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```
# Ansible Configuration:

```
[defaults]

jinja2_extensions = jinja2.ext.loopcontrols
inventory      = hosts

# uncomment this to disable SSH key host checking
host_key_checking = False

# SSH timeout
timeout = 10

# default user to use for playbooks if user is not specified
# (/usr/bin/ansible will use current user as default)
remote_user = root

# logging is off by default unless this path is defined
# if so defined, consider logrotate
#log_path = /var/log/ansible.log

# default module name for /usr/bin/ansible
module_name = setup

# use this shell for commands executed under sudo
# you may need to change this to bin/bash in rare instances
# if sudo is constrained
#executable = /bin/sh

# if inventory variables overlap, does the higher precedence one win
# or are hash values merged together?  The default is 'replace' but
# this can also be set to 'merge'.
#hash_behaviour = replace

# list any Jinja2 extensions to enable here:
#jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n

# if set, always use this private key file for authentication, same as 
# if passing --private-key to ansible or ansible-playbook
#private_key_file = /path/to/file


# the http user-agent string to use when fetching urls. Some web server
# operators block the default urllib user agent as it is frequently used
# by malicious attacks/scripts, so we set it to something unique to 
# avoid issues.
#http_user_agent = ansible-agent

# if set to a persistent type (not 'memory', for example 'redis') fact values
# from previous runs in Ansible will be stored.  This may be useful when
# wanting to use, for example, IP information from one group of servers
# without having to talk to them in the same playbook run to get their
# current IP information.
fact_caching = memory


# retry files
#retry_files_enabled = False
#retry_files_save_path = ~/.ansible-retry
```
# Environment:

I run Ansible from Mac OS X Yosemite, and I manage a fedora 22 Beta server
# Summary:

I can't use properly the dnf module, each time that I want to install a program, I have an error
# Steps To Reproduce:

```
- name: dnf test
  dnf: name=emacs-nox state=latest
```

```
ansible=playbook matrix.yml
```
# Expected Results:

Emacs installed and up to date
# Actual Results:

```
TASK: [fedora/22/common | dnf test] ******************************************* 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: root
<127.0.0.1> REMOTE_MODULE dnf name=emacs-nox state=latest
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/wowi/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=10022 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431186442.97-185397293418490 && echo $HOME/.ansible/tmp/ansible-tmp-1431186442.97-185397293418490'
<127.0.0.1> PUT /var/folders/tg/t4gnzkd919n20hxfpbhqsvh40000gn/T/tmp7FMfe8 TO /root/.ansible/tmp/ansible-tmp-1431186442.97-185397293418490/dnf
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/wowi/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=10022 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python -tt /root/.ansible/tmp/ansible-tmp-1431186442.97-185397293418490/dnf; rm -rf /root/.ansible/tmp/ansible-tmp-1431186442.97-185397293418490/ >/dev/null 2>&1'
failed: [matrixtest] => {"failed": true}
msg: Failure talking to dnf: 'Base' object has no attribute 'rpmdb'

FATAL: all hosts have already failed -- aborting
```

**Comment by ToBeReplaced** [comment]
I have the same issue. Nothing new to add, just indicating that it is affecting multiple users.

**Comment by abadger** [comment]
I tested this briefly on F21 and was unable to replicate it.  However, I do see a lot of problems in the code.  Can you tell me if repoquery is installed on your system?  (On F21, it's in the yum-utils package.  I don't know if it has moved since then.)  I think that I'm not hitting this error because repoquery is installed here.

It is a bit odd though... near as I can tell, the dnf module should install repoquery (via yum-utils) if it isn't present when the module is invoked.  Perhaps reoquery has moved to a different package?

**Comment by abadger** [comment]
Okay, if you don't have repoquery installed then I do see what's happening with it.  We're installing the dnf version of repoquery (which is a dnf plugin) but we're still checking for /usr/bin/repoquery.   The code needs to be modified to use the dnf plugin version instead.

**Comment by abadger** [comment]
Started updating the code but ran into issues right away.  For instance, the dnf repoquery plugin doesn't have --pkgnarrow: https://bugzilla.redhat.com/show_bug.cgi?id=1199601

**Comment by martin-ueding** [comment]
I also have errors with the `dnf` module. I tried to install some packages and got the following error:

```
TASK: [package-install | Install Fedora >= 22 packages] *********************** 
failed: [localhost] => (item=ansible) => {"failed": true, "item": "ansible", "parsed": false}
Traceback (most recent call last):
  File "/home/mu/.ansible/tmp/ansible-tmp-1432494998.14-18049635811979/dnf", line 2432, in <module>
    main()
  File "/home/mu/.ansible/tmp/ansible-tmp-1432494998.14-18049635811979/dnf", line 828, in main
    disablerepo, disable_gpg_check)
  File "/home/mu/.ansible/tmp/ansible-tmp-1432494998.14-18049635811979/dnf", line 745, in ensure
    my = dnf_base(conf_file)
  File "/home/mu/.ansible/tmp/ansible-tmp-1432494998.14-18049635811979/dnf", line 149, in dnf_base
    cachedir = cachedir.dnf.Conf()
AttributeError: 'bool' object has no attribute 'dnf'


FATAL: all hosts have already failed -- aborting
```

I try to apply just a single role to localhost on a Fedora 22 Beta VM. `roles/ansible-master/meta/main.yml`:

``` yaml
dependencies:
  - role: package-install
    list_Debian:
      - ansible
    list_Fedora:
      - ansible
```

This then installs the packages using `dnf`:

`roles/package-install/tasks/main.yml`

``` yaml
- name: Install Fedora >= 22 packages
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '22'
  action: dnf name={{ item }} state=installed
  with_items: list_Fedora
```

I have the `package-install` role because I have quite a distribution zoo here. All the roles are in [my playbooks repo](https://github.com/martin-ueding/playbooks).

To get the packages installed I could just use the `yum` module, but that complains that I should use `dnf` instead :-).

I use Ansible 1.9.1 from Fedora 22 Beta.

**Comment by andmalc** [comment]
I get the same error as reported by martin-ueding, also on Fedora 22 Beta running ansible 1.9.1, using the following bare-bones playbook:
- hosts: vps
  tasks: 
  - name: Update 
    dnf: name=\* state=latest

**Comment by abadger** [comment]
I'm seeing at least two separate bugs here.

The original report has the error `msg: Failure talking to dnf: 'Base' object has no attribute 'rpmdb'`.  For anyone suffering from that bug, I need to know if you have /usr/bin/repoquery on the system.  If not, whether installing the yum-utils package to get repoquery makes that error go away.

For the others getting the message: `AttributeError: 'bool' object has no attribute 'dnf'` I think this is an error I saw when trying to run the module as a non-root user.  It is a programming bug but if you run as root I think that it will go away.  There is a rewrite of the dnf module here: https://github.com/ansible/ansible-modules-extras/pull/527  I can see if there's something I can backport from that to make the cache error go away but there are other issues with the code that we might not be able to paper over so easily.  I'll see what I can do but we're going to need to get that rewrite of the module feature complete in order to really fix everything in here.

**Comment by andmalc** [comment]
@abadger 

You're correct: I wasn't running with sudo and doing so resolved 'AttributeError: 'bool' object has no attribute 'dnf''

Then I got 'msg: Failure talking to dnf: 'Base' object has no attribute 'rpmdb''  Installing yum-utils resolved that also!

**Comment by abadger** [comment]
@andmalc Thanks!  Judging from what you said, I think the changes I've just pushed will solve the issues described here.

Part of this is a backport from the rewrite in #527 and should solve the cache error.  The other part is making sure that yum-utils is installed in order to run this module.  Since most of the fallback code I see in this module won't work (because it is yum API rather than dnf API) we need repoquery from yum-utils at this time.

These are just bandaids until the rewrite of the dnf module in #527 is feature complete.  Once that happens we should be able to use this module with just dnf.  The requirement for yum-utils and the dnf repoquery replacement will go away.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by tadman** [comment]
Found a work-around for the `'Base' object has no attribute` problem by force-installing `repomanage` manually:

```
- name: Install Yum Utilities
  sudo: true
  shell: dnf install yum-utils -y
  args:
    creates: /usr/bin/repomanage
```

If that's present, installation continues normally.

**Comment by Fale** [comment]
In F22 installing yum-utils does not solve for me:

failed: [192.168.1.152] => (item=libselinux-python,libsemanage-python) => {"failed": true, "item": "libselinux-python,libsemanage-python"}
msg: Error from repoquery: ['/usr/bin/repoquery', '--show-duplicates', '--plugins', '--quiet', '-q', '--qf', '%{name}-%{version}-%{release}.%{arch}', 'libsemanage-python']: 
Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.

**Comment by wstrange** [comment]
F22, yum-utils installed, same issue for me

**Comment by abadger** [comment]
Unfortunately the fedora packages seem to have changed the implementation
of repoquery leading to that error. If you could try the dnf module from
the devel repo and it works perhaps that could be backported to the fedora
package.  The dnf module in devel is a rewrite of the module so it's
unlikely to be added to the 1.9.x upstream ansible package but additional
testing will help ensure that there's fewer bugs when ansible 2.0 is
released and will provide useful feedback that the downstream fedora
packagers can use to decide whether to package it as a backport to their
package.

**Comment by nirik** [comment]
Those folks still seeing this, can you note what exact version of ansible you are using on your control host? rpm -q ansible ? Also, on the target host is 'python-dnf' installed? Finally what exact command line/task duplicates what you are seeing?
